services:
  mqtt_distributor:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/altepizza/mqtt_broadcaster:latest
    restart: unless-stopped
    environment:
      - MQTT_DISTRIBUTER_BROKERPORT=${MQTT_BROKER_HOST_PORT}
      - MQTT_DISTRIBUTER_BROKERHOST=${MQTT_BROKER_HOST_URL}
      - MQTT_DISTRIBUTER_USERNAME=${MQTT_USERNAME}
      - MQTT_DISTRIBUTER_PASSWORD=${MQTT_PASSWORD}
      - MQTT_DISTRIBUTER_SOURCEPREFIX=${MQTT_SOURCE_TOPIC_PREFIX}
      - MQTT_DISTRIBUTER_TARGETPREFIXES=${MQTT_TARGET_TOPIC_PREFIXES}
